version: '3'

services:
  web:
    build:
      context: ./docker/web
    image: tiwvstiw${APP_ROOT}_web:$IMAGE_VERSION
    ports:
      - "0:80"
    volumes:
      - public:$APP_ROOT/public
      - sockets:$APP_ROOT/sockets
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: cicdpipe/web
        awslogs-stream-prefix: "web"
    depends_on: 
      - app

  app:
    # ecs-cliでbuildはサポート対象外なため無視される
    build:
      # buildでenvironmentを参照できないのでargsを使う
      args:
        - APP_ROOT=$APP_ROOT
        - BUILD_CONTEXT=production
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: tiwvstiw${APP_ROOT}_app:$IMAGE_VERSION
    environment:
      - RAILS_LOG_TO_STDOUT=true
    volumes:
      - public:$APP_ROOT/public
      - sockets:$APP_ROOT/tmp/sockets
      - bundle:/bundle
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: cicdpipe/app
        awslogs-stream-prefix: "app"
    command: /bin/sh -c "./docker/app/entrypoint.sh"

volumes:
  public:
  sockets:
  bundle:
